- name: variables form inventory
  hosts: local
  connections: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Hello i am learing {{COURSE}}, Duration: {{DURATION}}, Trainer is : {{TRAINER}}"